In [21]:
import numpy as np
import cv2
from IPython.display import clear_output, Image, display, HTML
import ipywidgets as widgets
import threading
import numpy as np
import matplotlib.pyplot as plt

# Repeatability
np.random.seed(0)

In [22]:
#filename = "walking.mp4"
filename = "Trafic.mp4"
frame_height = 720
frame_width = 1280

In [23]:
# Create a VideoCapture object and read from input file
# If the input is the camera, pass 0 instead of the video file name
cap = cv2.VideoCapture(filename)

fps = int(cap.get(cv2.CAP_PROP_FPS))
print(f"{fps} frames per second")

# Check if camera opened successfully
if (cap.isOpened()== False): 
  print("Error opening video stream or file")
 
# Read until video is completed
while(cap.isOpened()):
  # Capture frame-by-frame
  ret, frame = cap.read()

  if ret == True:
    # Display the resulting frame
    cv2.imshow('Frame',frame)
 
    # Press Q on keyboard to  exit
    if cv2.waitKey(30) & 0xFF == ord('q'):
      break
 
  # Break the loop
  else: 
    break
 
# When everything done, release the video capture object
cap.release()
 
# Closes all the frames
cv2.destroyAllWindows()

10 frames per second


In [24]:
def get_frames(filename):
    video = cv2.VideoCapture(filename)
    while video.isOpened():
        ret, frame = video.read()
        if ret:
            yield frame 
        else:
            break
    video.release()        
    yield None

In [25]:
def display(frame, particles, location):
    if len(particles)> 0:
        for i in range(NUM_PARTICLES):
            x = int(particles[i,0])
            y = int(particles[i,1])
            cv2.circle(frame, (x,y), 1 , (0,255,0) ,3)
    
    if len(location) > 0:
        cv2.circle(frame, location,15,(0,0,255),5)
    
    cv2.imshow('frame', frame)
    #stop the video if pressing q button
    if cv2.waitKey(30) & 0xFF == ord('q'):
        return True 

    return False

In [26]:
NUM_PARTICLES = 500
VEL_RANGE = 0.5

def initialize_particles():
    particles = np.random.rand(NUM_PARTICLES,4)
    particles = particles * np.array((frame_width,frame_height, VEL_RANGE,VEL_RANGE))
    particles[:,2:4] -= VEL_RANGE/2.0
    return particles



In [27]:
def apply_velocity(particles):
    particles[:,0] += particles[:,2]
    particles[:,1] += particles[:,3]

    return particles

In [28]:
# Display moving particles on video
location = []
particles = initialize_particles()


for frame in get_frames(filename):
    if frame is None: break
    particles = apply_velocity(particles)

    terminate = display(frame, particles, location)
    if terminate:
        break

cv2.destroyAllWindows()   

In [29]:
def enforce_edges(particles):
    for i in range(NUM_PARTICLES):
        particles[i,0] = max(0,min(frame_width-1, particles[i,0]))
        particles[i,1] = max(0,min(frame_height-1, particles[i,1]))
    return particles

In [42]:
#TARGET_COLOR = np.array((66,63, 105))
TARGET_COLOR = np.array((100,0, 100))

def compute_errors(particles, frame):
    
    errors = np.zeros(NUM_PARTICLES)
    for i in range(NUM_PARTICLES):
        x = int(particles[i,0])
        y= int(particles[i,1])
        pixel_color = frame[y, x, :]
        errors[i] = np.sum((TARGET_COLOR - pixel_color)**2)
    return errors
print(frame.shape)

(900, 1908, 3)


In [43]:
print(particles)
def compute_weights(errors):
    weights = np.max(errors) - errors
    
    weights[
        (particles[:,0]==0) |
        (particles[:,0]==frame_width-1) |
        (particles[:,1]==0) |
        (particles[:,1]==frame_height-1) ] = 0  
    
    weights = weights**32
    print(particles)
    return weights

[[ 1.24526120e+02  9.39954651e+01  2.24873131e-01 -4.99969359e-01]
 [ 1.23815534e+02  9.31325310e+01 -1.19005179e-01  3.37974241e-01]
 [ 1.28078761e+02  9.72007511e+01 -2.56429636e-01 -2.82273869e-01]
 ...
 [ 1.30162143e+02  9.61844642e+01  4.40509395e-01  2.77477075e-03]
 [ 1.30576604e+02  9.34513362e+01  1.84033247e-01  6.94641731e-02]
 [ 1.27319499e+02  9.77130497e+01 -1.46770630e-01  9.91608928e-02]]


In [44]:
def resample(particles, weights):
    probabilities = weights / np.sum(weights)
    index_numbers = np.random.choice(
        NUM_PARTICLES,
        size=NUM_PARTICLES,
        p=probabilities)
    particles = particles[index_numbers, :]
    
    x = np.mean(particles[:,0])
    y= np.mean(particles[:,1])
    return particles, [int(x), int(y)]


In [45]:
POS_SIGMA = 0.75
VEL_SIGMA = 0.1

def apply_noise(particles):
    noise= np.concatenate(
    (
        np.random.normal(0.0, POS_SIGMA, (NUM_PARTICLES,1)),
        np.random.normal(0.0, POS_SIGMA, (NUM_PARTICLES,1)),
        np.random.normal(0.0, VEL_SIGMA, (NUM_PARTICLES,1)),
        np.random.normal(0.0, VEL_SIGMA, (NUM_PARTICLES,1))
    
    ),
    axis=1)
    
    particles += noise
    return particles

In [46]:
particles = initialize_particles()

for frame in get_frames(filename):
    if frame is None: break

    particles = apply_velocity(particles)
    particles = enforce_edges(particles)
    errors = compute_errors(particles, frame)
    weights = compute_weights(errors)
    particles, location = resample(particles, weights)
    particles = apply_noise(particles)
    terminate = display(frame, particles, tuple(location))
    if terminate:
        break
cv2.destroyAllWindows()

[[ 5.77958828e+00  6.86174191e+02 -1.90146682e-01 -1.30944291e-01]
 [ 7.85628559e+02  2.87508817e+02  2.28251029e-01 -1.59015230e-04]
 [ 3.95748078e+01  2.87474325e+02 -1.90775423e-01 -5.24313683e-02]
 ...
 [ 7.63450210e+01  1.96102557e+02  1.04630648e-01  9.86304672e-02]
 [ 9.83291463e+02  3.50030566e+02 -1.09352183e-01  1.59921815e-01]
 [ 4.71522497e+02  1.20118133e+02  1.80482388e-01 -1.67951798e-01]]
[[ 1.02169733e+03  3.06594974e+02  9.57907502e-02  1.78325033e-01]
 [ 4.58582386e+02  3.61862507e+01 -1.36097143e-01  7.71987850e-02]
 [ 9.11168660e+02  1.78779675e+02 -6.47790222e-03 -2.40339819e-01]
 ...
 [ 4.83390571e+02  3.97278913e+02 -1.99956722e-01 -2.38250532e-02]
 [ 8.53178606e+02  2.47105294e+02  3.22739229e-01 -1.32604860e-01]
 [ 2.86606884e+02  6.55429174e+02 -1.07380543e-01 -3.76205523e-02]]
[[ 1.12431702e+03  6.62754101e+02  1.64172689e-01 -3.23938139e-03]
 [ 9.35052823e+02  3.25342226e+02  1.30715067e-01  1.77449955e-01]
 [ 2.06083221e+02  5.07275806e+02 -3.56896476e-01 

[[ 7.96274635e+02  4.35684708e+02  2.07952407e-02  3.51341055e-01]
 [ 7.95891516e+02  4.32083306e+02 -2.14968378e-01  9.09121985e-02]
 [ 7.93814667e+02  4.37193636e+02 -4.76516812e-01  8.71841662e-01]
 ...
 [ 7.98076050e+02  4.32831798e+02  7.04513357e-01  1.89163025e-01]
 [ 7.95235120e+02  4.34061346e+02 -1.94653651e-01  4.57259788e-01]
 [ 7.95484886e+02  4.37166667e+02 -1.66080278e-01  1.04122897e+00]]
[[ 7.95348036e+02  4.30060477e+02  4.04186954e-02  4.13970505e-02]
 [ 7.97077219e+02  4.38177922e+02 -2.46489686e-02  9.72610770e-01]
 [ 7.94950692e+02  4.34673932e+02 -1.53284786e-01  3.37997105e-01]
 ...
 [ 7.95619317e+02  4.33004373e+02 -8.50316897e-02  6.15099688e-01]
 [ 7.95895803e+02  4.37222106e+02 -4.14600484e-01  1.27855195e-01]
 [ 7.96794756e+02  4.35714128e+02 -1.73077167e-01  4.63760746e-01]]
[[ 7.97013143e+02  4.36114271e+02  1.33826024e-01  3.45190951e-01]
 [ 7.95049711e+02  4.30213333e+02 -7.04198630e-02  2.16212985e-02]
 [ 7.97607111e+02  4.31160376e+02  1.22735327e-01 

[[ 7.97517372e+02  4.35610124e+02  6.48779221e-01  9.41813962e-02]
 [ 7.96829806e+02  4.34142591e+02 -5.04646259e-01 -3.32366316e-01]
 [ 7.99184621e+02  4.36990597e+02  4.88080042e-01 -4.97395456e-02]
 ...
 [ 7.94986224e+02  4.36639483e+02 -6.90021553e-02  2.34738446e-01]
 [ 7.98206293e+02  4.34438333e+02 -3.34753803e-02  7.96109610e-02]
 [ 7.97483594e+02  4.37500684e+02 -1.66202750e-01 -8.79621510e-02]]
[[ 7.96741825e+02  4.34553747e+02  9.62329279e-02  2.79028633e-01]
 [ 7.98999544e+02  4.33992528e+02  2.14372598e-01  5.13667163e-01]
 [ 7.98648167e+02  4.34056017e+02  1.89340564e-01 -2.80074632e-01]
 ...
 [ 7.97565366e+02  4.37906839e+02  3.78144590e-01  8.59693106e-02]
 [ 7.96252765e+02  4.27587664e+02 -1.23564758e-02 -6.41530815e-01]
 [ 7.98581986e+02  4.31911436e+02 -8.97365161e-02 -2.80389365e-01]]
[[ 7.98031046e+02  4.37296636e+02  3.04607043e-02  6.27202018e-01]
 [ 7.97981803e+02  4.33871803e+02  3.87660553e-01  4.01651942e-01]
 [ 7.97842497e+02  4.38564515e+02 -3.96675602e-01 

[[ 7.95786929e+02  4.36135954e+02 -2.50475098e-02  7.77935194e-01]
 [ 7.93608477e+02  4.34178161e+02 -2.75939355e-02  1.19646576e-01]
 [ 7.93511861e+02  4.29522487e+02 -5.34581023e-02  2.06369612e-01]
 ...
 [ 7.97068470e+02  4.34179054e+02 -1.85674024e-01  2.45044645e-01]
 [ 7.97745897e+02  4.38560210e+02 -8.49140900e-03  5.04383646e-01]
 [ 7.97018474e+02  4.31840996e+02 -1.06698827e-01 -5.86742872e-01]]
[[ 7.94434875e+02  4.28783297e+02 -1.47642769e-02  4.26019518e-01]
 [ 7.95980933e+02  4.34661017e+02 -3.27435767e-01  5.53053834e-01]
 [ 7.94723484e+02  4.28237902e+02 -5.82437891e-01 -2.36265509e-01]
 ...
 [ 7.98312301e+02  4.34374553e+02 -3.56952154e-01  6.12331505e-03]
 [ 7.93709494e+02  4.27898826e+02 -3.45854417e-01 -1.12910100e-01]
 [ 7.95979578e+02  4.31924770e+02 -1.44504791e-01  2.67284844e-01]]
[[ 7.97691712e+02  4.37557060e+02 -3.21752410e-02  4.88716430e-01]
 [ 7.97413609e+02  4.31328665e+02 -6.20076880e-02 -1.43062811e-01]
 [ 7.96054959e+02  4.34170003e+02  1.24234929e-01 

[[ 7.98678606e+02  4.32426074e+02  1.74172282e-01 -3.69432083e-01]
 [ 7.98130555e+02  4.35015119e+02 -1.77103095e-01  2.14156806e-01]
 [ 7.99784579e+02  4.33907957e+02  2.19780517e-01  2.68299097e-02]
 ...
 [ 7.97931462e+02  4.35703529e+02 -1.67689498e-01  7.81802466e-02]
 [ 7.98657131e+02  4.35965760e+02  2.60853769e-01  5.82883665e-01]
 [ 7.96612788e+02  4.35681720e+02 -5.61092594e-01 -3.35099762e-01]]
[[ 7.96799745e+02  4.32231513e+02  1.62261515e-01 -3.21670231e-02]
 [ 7.98727879e+02  4.34274253e+02  9.54020297e-01  1.51061017e-01]
 [ 7.95449643e+02  4.34567883e+02 -4.48579630e-01  2.22572878e-01]
 ...
 [ 7.96843459e+02  4.33208035e+02 -2.66845993e-01 -2.58910625e-01]
 [ 7.96104361e+02  4.32337175e+02 -6.95696120e-01 -8.94132219e-01]
 [ 7.97535830e+02  4.36803252e+02  4.78232542e-01  1.38079259e-01]]
[[ 7.97387739e+02  4.34455860e+02 -1.02577725e-01 -8.71443714e-02]
 [ 7.99741186e+02  4.32906869e+02 -2.30795375e-01 -7.88605511e-02]
 [ 7.98961990e+02  4.36769519e+02 -1.45005120e-02 

[[ 7.98150985e+02  4.30376001e+02 -1.19439886e-01 -6.27626694e-01]
 [ 7.97096863e+02  4.30977594e+02  1.64938223e-01 -3.83494967e-01]
 [ 7.97448198e+02  4.30029215e+02  3.65443247e-02 -3.35488848e-01]
 ...
 [ 7.96740606e+02  4.28652801e+02 -2.63308202e-01 -4.35817363e-01]
 [ 7.97523292e+02  4.30700053e+02  3.26338348e-01 -1.94090251e-01]
 [ 7.98774317e+02  4.31750626e+02  2.00862801e-01 -1.02798323e-01]]
[[ 7.96554707e+02  4.36681680e+02  1.69482379e-01  6.09476265e-01]
 [ 7.96697543e+02  4.30884988e+02 -8.38821207e-02 -2.58406927e-01]
 [ 7.95135618e+02  4.29198370e+02 -3.24760349e-01 -2.05124876e-01]
 ...
 [ 7.94656291e+02  4.38865482e+02  1.87082062e-01  7.15207418e-01]
 [ 7.96258378e+02  4.30398864e+02  1.36860972e-01 -3.63689015e-02]
 [ 7.93927220e+02  4.38390816e+02  2.77041631e-01  5.38684676e-01]]
[[ 7.97611308e+02  4.30601532e+02  1.27128845e-01 -2.44647893e-01]
 [ 7.95262640e+02  4.32067690e+02 -8.48574063e-02 -3.82869862e-01]
 [ 7.99408642e+02  4.31012085e+02  1.81434704e-01 

[[ 7.98503971e+02  4.33433421e+02 -4.04463470e-01 -9.32185594e-03]
 [ 7.95613416e+02  4.34727869e+02  2.35478580e-01 -1.41044545e-01]
 [ 7.95525154e+02  4.38422503e+02 -4.72377997e-01 -5.30610847e-02]
 ...
 [ 7.98295697e+02  4.32508856e+02  2.50094852e-01 -1.34577119e-02]
 [ 7.98367064e+02  4.33363350e+02  3.08947070e-01 -1.35479560e-01]
 [ 7.95963218e+02  4.33629998e+02 -1.88917474e-01  1.50877989e-01]]
[[ 7.98387460e+02  4.37859143e+02 -4.18471981e-01  4.70564127e-01]
 [ 7.97193760e+02  4.33851319e+02  2.74701253e-01 -3.64421427e-02]
 [ 7.97224423e+02  4.35232192e+02  9.16570194e-02 -3.89331332e-01]
 ...
 [ 7.96291176e+02  4.35505706e+02 -9.34854847e-02  4.76991566e-01]
 [ 7.98631246e+02  4.37397406e+02 -9.66655708e-03  4.82617917e-01]
 [ 7.95107328e+02  4.31740900e+02 -1.71458560e-01 -6.60875655e-03]]
[[ 7.95144955e+02  4.30748370e+02 -2.95267305e-01 -2.31717988e-01]
 [ 7.97338284e+02  4.36164494e+02  4.51265756e-01  1.14706817e-01]
 [ 7.95986823e+02  4.36619505e+02  9.04737124e-04 

[[ 7.96602178e+02  4.36881374e+02 -1.62913405e-02  3.97492868e-01]
 [ 7.95472201e+02  4.38201242e+02  1.76652502e-02  2.03677459e-01]
 [ 7.98403824e+02  4.33592906e+02 -1.69242478e-01  5.58448936e-02]
 ...
 [ 7.96452085e+02  4.34573589e+02 -2.22560155e-01  6.60081428e-01]
 [ 7.95918057e+02  4.31040104e+02 -4.67155838e-01  6.51843873e-02]
 [ 7.98202814e+02  4.33067674e+02  6.69390684e-02  1.40372560e-01]]
[[ 7.97555835e+02  4.34463779e+02  5.52573626e-01  1.07844540e-01]
 [ 8.00038848e+02  4.34533754e+02  2.88722193e-01  1.55665910e-02]
 [ 7.96601518e+02  4.35454890e+02  4.32812098e-01  2.47171618e-01]
 ...
 [ 7.99081053e+02  4.33877912e+02  1.91002534e-01  9.18196730e-02]
 [ 7.96810310e+02  4.37614578e+02 -2.79913843e-01  2.60154113e-01]
 [ 7.97598041e+02  4.35297772e+02 -3.33836370e-01  2.86976256e-01]]
[[ 7.96289870e+02  4.37110084e+02 -7.43539020e-02  4.01503222e-01]
 [ 7.97406654e+02  4.39821016e+02  7.45801040e-01  2.01823892e-01]
 [ 7.98073706e+02  4.36829427e+02  1.78868103e-01 

[[ 7.95677406e+02  4.32257152e+02 -1.42246561e-01 -5.30425597e-01]
 [ 7.95851867e+02  4.33643191e+02  4.25519193e-02 -3.44725764e-01]
 [ 7.98148796e+02  4.31403243e+02  3.42957946e-01 -3.09118138e-01]
 ...
 [ 7.95660849e+02  4.33075275e+02 -3.12828133e-01 -2.39929523e-01]
 [ 7.97663363e+02  4.33905762e+02 -1.22373165e-01 -1.74528693e-01]
 [ 7.97096692e+02  4.33385976e+02 -9.10450602e-02 -2.38995231e-01]]
[[ 7.97534646e+02  4.35498056e+02 -1.14204132e-01  1.66078715e-01]
 [ 7.98365769e+02  4.32030587e+02 -3.80595393e-01 -3.00548481e-01]
 [ 7.98221546e+02  4.31199520e+02  1.52907303e-01 -2.06026087e-01]
 ...
 [ 7.98615771e+02  4.33893598e+02  3.87988735e-01  3.46584143e-01]
 [ 7.99134699e+02  4.31711251e+02  6.29905753e-02 -7.85449065e-01]
 [ 7.96866780e+02  4.32920836e+02 -1.30765338e-01  3.46070375e-02]]
[[ 7.99292154e+02  4.33099957e+02 -5.59040451e-02 -3.45244985e-01]
 [ 7.99740942e+02  4.32920844e+02  9.76589279e-02 -1.52927625e-01]
 [ 7.97623213e+02  4.32092759e+02 -3.99009599e-01 

[[ 7.99343293e+02  4.32740262e+02  8.87011888e-02 -2.18092667e-01]
 [ 7.97636460e+02  4.29773354e+02 -5.15689263e-01 -3.73076415e-01]
 [ 7.97335174e+02  4.31965445e+02 -2.97816748e-01 -9.58087115e-02]
 ...
 [ 7.96622673e+02  4.37333341e+02  8.76004904e-02  2.30603057e-01]
 [ 7.99028248e+02  4.31862002e+02 -1.00578046e-01 -3.33762506e-01]
 [ 7.95263476e+02  4.35844545e+02 -4.50860968e-01  3.65103479e-01]]
[[ 7.97993990e+02  4.34191887e+02 -6.08959170e-01  6.59115809e-02]
 [ 7.97082452e+02  4.34939015e+02 -3.45518926e-01  2.66122707e-01]
 [ 7.98868580e+02  4.33201192e+02 -5.39446394e-01 -1.60870115e-01]
 ...
 [ 7.97688602e+02  4.34623872e+02 -2.51789921e-01 -1.76099152e-01]
 [ 7.98086036e+02  4.34528743e+02 -2.96539569e-01 -3.91986243e-01]
 [ 7.96715803e+02  4.35013123e+02 -1.77284035e-01  7.58337757e-01]]
[[ 8.00900642e+02  4.33764223e+02  1.83161073e-01 -1.54236502e-01]
 [ 7.96141567e+02  4.35116802e+02 -2.16808525e-01  5.57359672e-01]
 [ 7.97065224e+02  4.32087069e+02 -4.43023762e-01 

[[ 7.97102349e+02  4.35528911e+02 -1.66156839e-01 -4.84896441e-02]
 [ 7.98237868e+02  4.33529906e+02 -2.40682818e-01  3.39699548e-01]
 [ 7.96853877e+02  4.37163799e+02  6.26014154e-02 -3.59483062e-01]
 ...
 [ 7.97400682e+02  4.34709989e+02  2.71517904e-01 -2.99820836e-01]
 [ 7.98037202e+02  4.34487920e+02 -2.50173558e-02 -2.18123961e-02]
 [ 7.96717530e+02  4.35224114e+02 -2.11776597e-01  1.84538541e-01]]
[[ 7.96933140e+02  4.37921657e+02 -6.36675978e-02 -3.01838150e-01]
 [ 7.96816190e+02  4.36920931e+02 -8.75088672e-02  3.38463430e-01]
 [ 7.95099625e+02  4.36137782e+02  7.79460760e-03 -2.27537919e-02]
 ...
 [ 7.97171481e+02  4.36239655e+02 -2.86564018e-02  3.36422948e-01]
 [ 7.95808493e+02  4.34691625e+02 -6.15495922e-01 -3.45851843e-01]
 [ 7.98435656e+02  4.36586834e+02  2.96652591e-01  3.05912784e-01]]
[[ 7.96041179e+02  4.36841628e+02  3.87840976e-01  1.57984028e-01]
 [ 7.98660682e+02  4.32892655e+02 -1.60744832e-01  2.89983652e-01]
 [ 7.94566636e+02  4.35999026e+02 -5.92503713e-01 

[[ 7.96351469e+02  4.36581666e+02  6.48711323e-03  1.26335822e-01]
 [ 7.95574996e+02  4.35836494e+02  3.16665651e-01  1.40422743e-02]
 [ 7.96389570e+02  4.39209636e+02 -7.96481050e-02  1.49083883e-01]
 ...
 [ 7.95406954e+02  4.35207224e+02 -2.44437423e-01 -3.67936251e-01]
 [ 7.96112839e+02  4.34908141e+02  1.65221029e-01 -2.49919568e-01]
 [ 7.94840228e+02  4.32076420e+02 -1.78446684e-01 -8.47297351e-01]]
[[ 7.95384917e+02  4.36890915e+02  4.38160613e-04 -4.23306035e-01]
 [ 7.93474432e+02  4.38504413e+02 -4.24439419e-01 -4.86550798e-03]
 [ 7.97254166e+02  4.37630730e+02  1.00691207e-01  3.27360389e-01]
 ...
 [ 7.94234758e+02  4.37702593e+02  1.71052730e-01  2.71008485e-01]
 [ 7.94521289e+02  4.38655371e+02 -8.96505217e-02  1.90479078e-01]
 [ 7.94895089e+02  4.34925371e+02 -1.69104809e-01 -5.08563944e-01]]
[[ 7.97497997e+02  4.34930234e+02  3.30170416e-02 -7.12810436e-01]
 [ 7.95051474e+02  4.34979436e+02 -5.04711638e-01 -2.07569458e-01]
 [ 7.96142582e+02  4.35200017e+02  4.39399534e-01 

[[ 7.95762318e+02  4.37903391e+02  1.00613530e-01 -1.85305733e-01]
 [ 7.95160208e+02  4.32172409e+02 -7.52688426e-01  1.35209429e-01]
 [ 7.97688174e+02  4.32966750e+02 -8.28996374e-02  3.65409562e-01]
 ...
 [ 7.98432784e+02  4.34516501e+02  5.43920646e-01 -2.06398223e-01]
 [ 7.97059106e+02  4.30452431e+02  1.41920310e-01  1.08095875e-01]
 [ 7.97335998e+02  4.32588824e+02 -1.70528629e-01 -4.02924407e-01]]
[[ 7.95196171e+02  4.36468437e+02 -9.90132254e-02  6.77322410e-02]
 [ 7.95211206e+02  4.34558335e+02 -3.49054661e-01 -2.84903414e-01]
 [ 7.96385111e+02  4.39268555e+02  1.92385676e-01  6.17466738e-01]
 ...
 [ 7.95592115e+02  4.36675003e+02 -5.14667723e-01 -8.19571052e-02]
 [ 7.95550963e+02  4.35238171e+02 -5.94993027e-01 -2.58344530e-01]
 [ 7.95081524e+02  4.38797337e+02  3.50398024e-01  1.06243669e+00]]
[[ 7.96753028e+02  4.34513960e+02 -3.71569232e-01 -4.66609711e-01]
 [ 7.97110689e+02  4.31543367e+02 -3.17950962e-01 -6.57877233e-01]
 [ 7.95541206e+02  4.38754854e+02 -4.41855586e-01 

[[ 7.96296508e+02  4.29715880e+02 -4.74831157e-01 -1.14024866e-01]
 [ 7.95576968e+02  4.29334041e+02 -1.26039735e-01 -3.05960101e-01]
 [ 7.95476285e+02  4.31051467e+02 -5.12214876e-02 -2.76637056e-01]
 ...
 [ 7.94037322e+02  4.28958940e+02 -9.36042284e-02 -2.08596613e-01]
 [ 7.97098867e+02  4.31225017e+02  2.49104040e-01 -6.24291274e-02]
 [ 7.93695450e+02  4.30166029e+02  1.81381348e-01 -2.19552148e-01]]
[[ 7.96675220e+02  4.31157937e+02  4.82602862e-01  1.77853235e-03]
 [ 7.97147193e+02  4.30439182e+02  3.99906728e-01  5.13487099e-01]
 [ 7.96496206e+02  4.31066633e+02  1.71599699e-01 -2.89324074e-01]
 ...
 [ 7.93711583e+02  4.27601137e+02  7.48686663e-02 -3.03706397e-01]
 [ 7.95553372e+02  4.30539365e+02  3.65142425e-01  2.29653357e-01]
 [ 7.96377518e+02  4.31406249e+02  2.55024320e-01  5.68244461e-01]]
[[ 7.96907371e+02  4.31069444e+02  2.26569786e-01 -3.99837697e-01]
 [ 7.97933081e+02  4.30308692e+02  5.09892422e-01 -1.54115323e-01]
 [ 7.97421502e+02  4.30676338e+02  6.01788473e-02 

[[ 7.95934871e+02  4.32427998e+02  4.63229311e-01  9.11917205e-03]
 [ 7.95566350e+02  4.31756358e+02  3.36097824e-01  1.09871082e-01]
 [ 7.96088371e+02  4.29737920e+02 -3.87257236e-01 -5.03467787e-01]
 ...
 [ 7.98631904e+02  4.31507701e+02  3.43765913e-01  2.21860747e-01]
 [ 7.96910430e+02  4.31259642e+02  2.30488480e-01  3.17708509e-01]
 [ 7.96618882e+02  4.32628583e+02  5.43608788e-01  1.59446461e-01]]
[[ 7.96705367e+02  4.29719866e+02 -3.61351009e-01 -2.38646621e-02]
 [ 7.97175227e+02  4.30075734e+02  3.19226462e-01 -8.35182228e-02]
 [ 7.95369553e+02  4.31871439e+02  6.69020018e-02  2.36244299e-01]
 ...
 [ 7.95833551e+02  4.33710374e+02 -1.67242173e-01  5.58105778e-02]
 [ 7.97389707e+02  4.31688889e+02  6.52307184e-02  4.40295953e-01]
 [ 7.96199446e+02  4.29393806e+02 -3.13082108e-01 -3.85449087e-01]]
[[ 7.96534216e+02  4.30704604e+02  1.19881508e-01 -3.93297046e-02]
 [ 7.96910119e+02  4.30716161e+02 -2.58252220e-01  1.48143727e-01]
 [ 7.96687900e+02  4.29530580e+02  1.58386423e-01 

[[ 7.98592089e+02  4.33096231e+02  2.66058089e-01 -1.65185122e-01]
 [ 7.98227806e+02  4.36118964e+02 -1.64539315e-01  6.90534470e-01]
 [ 7.97639749e+02  4.32411104e+02  1.18077413e-02  6.71715103e-01]
 ...
 [ 7.97837630e+02  4.30836535e+02 -6.50320923e-02 -1.85156082e-01]
 [ 7.99847326e+02  4.33857937e+02  5.47791741e-01 -2.70442170e-01]
 [ 7.97094690e+02  4.34357072e+02 -7.36145369e-01  3.59868331e-01]]
[[ 7.97107852e+02  4.32937220e+02  5.49767962e-01  4.16872930e-01]
 [ 7.98422062e+02  4.37033320e+02 -2.28617995e-01  2.93030402e-01]
 [ 7.97942444e+02  4.32153305e+02  1.53364026e-01 -1.29124271e-01]
 ...
 [ 7.98512462e+02  4.32767559e+02 -2.80099098e-01  5.39003738e-01]
 [ 7.98085206e+02  4.35789399e+02  4.70061006e-02  3.75512874e-01]
 [ 7.97975425e+02  4.31114666e+02 -5.28789674e-02  3.97261522e-01]]
[[ 7.99096545e+02  4.36170322e+02  6.59515600e-02  1.98343184e-01]
 [ 7.97509187e+02  4.35904346e+02  4.45877948e-01  1.12501902e-01]
 [ 7.97574126e+02  4.35985235e+02 -8.03834706e-01 

[[ 7.98406186e+02  4.32118783e+02  3.46479935e-03  1.26875135e-01]
 [ 7.96897150e+02  4.38409605e+02  3.43089901e-01  4.35277700e-01]
 [ 7.97166221e+02  4.33024251e+02 -2.86346734e-01 -6.25460894e-01]
 ...
 [ 7.98044532e+02  4.37631198e+02 -1.86693081e-01  4.20456473e-01]
 [ 7.97410116e+02  4.36274625e+02 -5.05428518e-01 -3.35832214e-02]
 [ 8.00145417e+02  4.37296357e+02 -4.88200425e-01 -9.00041620e-02]]
[[ 7.96894847e+02  4.33045319e+02 -3.44974033e-01 -6.32010333e-01]
 [ 7.96743026e+02  4.38324077e+02  9.08777598e-02  2.93394508e-01]
 [ 7.95850374e+02  4.30208115e+02 -8.51689295e-02  3.64585228e-02]
 ...
 [ 7.97014958e+02  4.32887441e+02 -5.40675546e-01 -1.81137356e-01]
 [ 7.95762850e+02  4.37540868e+02  2.11660717e-01  1.06330741e-01]
 [ 7.96722957e+02  4.33788895e+02 -2.51854204e-01 -4.16580265e-03]]
[[ 7.96872055e+02  4.30787574e+02 -5.42055162e-02 -3.69507352e-01]
 [ 7.97320160e+02  4.31790198e+02 -3.94558001e-01 -2.31287732e-01]
 [ 7.98223306e+02  4.32677241e+02 -4.39133893e-02 

[[ 7.97443184e+02  4.34496991e+02 -1.85789443e-01  4.55488892e-02]
 [ 7.99286826e+02  4.33393496e+02  3.42410576e-01 -1.60428056e-01]
 [ 7.98380923e+02  4.35476964e+02  3.37615875e-01  3.95352510e-01]
 ...
 [ 7.99001099e+02  4.36861295e+02  4.47121629e-01  5.89390593e-01]
 [ 7.99173671e+02  4.34306182e+02 -5.39377871e-02  1.60658330e-01]
 [ 7.96258153e+02  4.32618243e+02  1.23721197e-01 -3.29991332e-02]]
[[ 7.97300364e+02  4.32287577e+02  5.11444799e-01  2.98914917e-01]
 [ 8.00665930e+02  4.34160068e+02  1.99929863e-01  2.36621868e-01]
 [ 7.95263875e+02  4.37776137e+02 -2.25354440e-01  6.77016512e-01]
 ...
 [ 7.99314458e+02  4.33929962e+02  4.03458108e-01  2.72090753e-01]
 [ 7.97488708e+02  4.34830141e+02  2.74314018e-01 -6.15246697e-02]
 [ 7.95992119e+02  4.31615873e+02 -2.24094945e-01  3.33284053e-01]]
[[ 7.96632523e+02  4.35495451e+02 -2.11872082e-01  5.35722096e-01]
 [ 7.95744886e+02  4.31374370e+02  3.32973380e-01 -1.56463834e-01]
 [ 7.96526078e+02  4.32266035e+02 -4.72005709e-01 

[[ 7.95413722e+02  4.37469482e+02 -5.70455701e-01  1.63015568e-01]
 [ 7.96738181e+02  4.33874050e+02 -5.30672285e-01  1.14322925e-01]
 [ 7.95343039e+02  4.34313755e+02 -3.15210568e-02  3.85896221e-01]
 ...
 [ 7.96385641e+02  4.38254709e+02 -1.17740915e-01  2.95675578e-01]
 [ 7.94457081e+02  4.35755211e+02 -5.71666191e-01  4.94600902e-01]
 [ 7.98313988e+02  4.36951536e+02  2.69975628e-01  6.82872669e-01]]
[[ 7.94601672e+02  4.38609561e+02  6.54479359e-03  1.44676240e-01]
 [ 7.94477084e+02  4.34052312e+02 -1.20234358e-01  3.18866635e-01]
 [ 7.96431845e+02  4.36753408e+02  2.66732346e-02  5.30089867e-01]
 ...
 [ 7.95025691e+02  4.36614922e+02 -1.93267967e-01  2.45855872e-01]
 [ 7.96594346e+02  4.32256980e+02 -2.28468222e-01 -3.76968330e-01]
 [ 7.95090620e+02  4.32663061e+02  1.29849570e-01  1.53801775e-01]]
[[ 7.95861161e+02  4.38624182e+02 -2.57864159e-01  1.60912633e-01]
 [ 7.99343047e+02  4.33018481e+02  2.29045081e-01  4.90217675e-02]
 [ 7.96182017e+02  4.36030848e+02  4.90717879e-01 

[[ 7.96041097e+02  4.33188152e+02  7.70050400e-02  1.75402309e-01]
 [ 7.97449282e+02  4.32536230e+02 -1.34353491e-01 -1.15662996e-01]
 [ 7.98918259e+02  4.32265811e+02  8.46858674e-02 -6.89569844e-01]
 ...
 [ 7.95415812e+02  4.35407922e+02 -3.54037861e-02 -2.04715922e-02]
 [ 7.96364994e+02  4.36132374e+02  2.87736360e-01 -3.51464289e-01]
 [ 7.98874927e+02  4.32293457e+02  4.83195570e-02 -4.34664418e-01]]
[[ 7.97146239e+02  4.35469952e+02  1.71435182e-01  2.94199790e-01]
 [ 7.99458741e+02  4.32733926e+02  3.58015339e-01  4.53280135e-01]
 [ 7.96797006e+02  4.35248898e+02  1.02278865e-02  3.98330912e-02]
 ...
 [ 7.98442908e+02  4.33684724e+02 -5.27472115e-02  1.68341612e-01]
 [ 7.99024615e+02  4.33906233e+02  1.38192303e-01  1.16801640e-02]
 [ 7.96868389e+02  4.34019552e+02 -6.57920194e-02 -2.67299033e-02]]
[[ 7.97931551e+02  4.33853950e+02 -2.28915279e-01  3.13630546e-01]
 [ 7.95448797e+02  4.34208503e+02 -3.36011536e-01  1.62731532e-02]
 [ 7.97886495e+02  4.33294949e+02  3.15585622e-01 

[[ 7.95678181e+02  4.32678845e+02 -4.59765232e-01 -4.49573098e-01]
 [ 7.95758885e+02  4.34056949e+02 -4.51730891e-01 -3.96424404e-01]
 [ 7.95152886e+02  4.29093002e+02 -1.32934590e-01 -2.42906618e-01]
 ...
 [ 7.95349740e+02  4.37312871e+02 -3.72484658e-01  5.72142015e-01]
 [ 7.98514188e+02  4.34567966e+02 -1.32905979e-01 -2.85056423e-01]
 [ 7.99822288e+02  4.33469702e+02  3.54368449e-02  4.40968206e-02]]
[[ 7.96389766e+02  4.30925045e+02 -4.85402509e-01  1.00895421e-01]
 [ 7.94091038e+02  4.38168149e+02 -3.01899922e-01  4.79330264e-01]
 [ 7.99075553e+02  4.34779196e+02  4.13635914e-01  5.91692450e-01]
 ...
 [ 7.98727533e+02  4.38672843e+02 -1.82581309e-01  8.03026806e-01]
 [ 7.96708848e+02  4.35389660e+02 -3.10845764e-01  5.14813374e-01]
 [ 7.98419685e+02  4.36887367e+02  3.64680942e-01  6.20595162e-01]]
[[ 7.94409503e+02  4.35181513e+02 -8.60125515e-02 -8.50550024e-02]
 [ 7.96781853e+02  4.31870367e+02 -3.18510795e-01 -2.62972865e-01]
 [ 7.94645822e+02  4.34194198e+02 -7.93221208e-01 

[[ 7.94370277e+02  4.35860338e+02 -3.98395748e-01 -1.11375137e-01]
 [ 7.97283269e+02  4.37458761e+02 -1.44408178e-01  4.75169185e-01]
 [ 7.95231222e+02  4.34825328e+02 -1.54003881e-01  2.61213831e-01]
 ...
 [ 7.96106153e+02  4.33656046e+02  4.49969131e-01  2.96927082e-01]
 [ 7.96237181e+02  4.34588454e+02 -1.17109037e-01  2.54954318e-01]
 [ 7.95627533e+02  4.38066174e+02 -1.52405556e-01  8.13529015e-01]]
[[ 7.97313704e+02  4.37502961e+02 -6.34056892e-02  5.56964181e-01]
 [ 7.96636995e+02  4.37904058e+02 -9.99563014e-02  2.59755129e-01]
 [ 7.95599540e+02  4.37588511e+02 -3.48864158e-01  3.50500755e-01]
 ...
 [ 7.94556763e+02  4.36468839e+02 -9.15645533e-02  3.07607909e-01]
 [ 7.95306473e+02  4.30878526e+02 -6.31493127e-02 -3.56398932e-01]
 [ 7.94309121e+02  4.36969679e+02 -2.66578022e-01  3.79335789e-02]]
[[ 7.97151522e+02  4.37552778e+02  3.03676161e-02  5.22873655e-01]
 [ 7.99181876e+02  4.32049122e+02 -4.45761665e-01 -2.03195869e-01]
 [ 7.95933633e+02  4.35718156e+02 -3.75849057e-02 

[[ 7.95566677e+02  4.36254755e+02 -3.17471101e-01 -1.89444221e-01]
 [ 7.99773419e+02  4.32943075e+02  4.70517531e-01  2.23720238e-01]
 [ 7.96374355e+02  4.34539368e+02  2.13573229e-01  6.34827690e-02]
 ...
 [ 7.97157181e+02  4.33290953e+02 -4.47579531e-01  1.49760651e-01]
 [ 7.96045578e+02  4.36591834e+02  2.84302068e-01  5.90490122e-01]
 [ 7.95047481e+02  4.34671860e+02 -1.43838042e-02  4.08119376e-01]]
[[ 7.96211441e+02  4.35560820e+02  3.84428704e-01  3.37899980e-01]
 [ 7.94216502e+02  4.29370639e+02 -4.61714951e-01 -5.08851561e-01]
 [ 7.96178212e+02  4.31118703e+02  1.75577048e-02  1.49014216e-01]
 ...
 [ 7.95423828e+02  4.36746884e+02  2.56975310e-01  4.59936100e-01]
 [ 7.96182620e+02  4.32597059e+02 -2.90190963e-01 -1.19421672e-01]
 [ 7.95593153e+02  4.33771342e+02  4.95352391e-01 -3.65668078e-01]]
[[ 7.98030269e+02  4.36252978e+02  2.80218623e-01  4.66690599e-01]
 [ 7.95535994e+02  4.35129996e+02  8.87003754e-02 -3.63599189e-01]
 [ 7.95792640e+02  4.37795551e+02  2.00716467e-01 

[[ 8.00237607e+02  4.51141086e+02 -2.62908418e-02  3.93070568e-01]
 [ 7.98689875e+02  4.50548349e+02  2.12852193e-01 -2.28187906e-01]
 [ 7.99716782e+02  4.50758612e+02 -8.45949364e-02  6.28204337e-01]
 ...
 [ 7.97638540e+02  4.51847462e+02  3.16089280e-01  2.12050317e-01]
 [ 7.99180237e+02  4.48707392e+02 -1.02500578e-01  3.39670576e-01]
 [ 8.01713247e+02  4.50144754e+02  3.94546738e-01  4.32503367e-01]]
[[ 7.99703752e+02  4.31664867e+02  1.56594468e-01 -3.23110419e-01]
 [ 7.99611442e+02  4.51247518e+02  5.66200301e-01  4.29342538e-01]
 [ 7.98936252e+02  4.51733220e+02  2.78736619e-01  4.04377410e-01]
 ...
 [ 7.99110702e+02  4.49665169e+02 -4.97918911e-02 -4.17596522e-02]
 [ 7.99842320e+02  4.49785654e+02  2.61775277e-01 -1.20271087e-02]
 [ 8.00093021e+02  4.50176026e+02 -6.28417699e-03  5.94122046e-01]]
[[ 7.98126332e+02  4.50060832e+02  3.50947471e-02  4.00952883e-01]
 [ 7.99875486e+02  4.53213180e+02  4.01152687e-01  6.92191344e-01]
 [ 7.89730916e+02  4.47551913e+02 -2.16221307e-01 

[[ 7.96336538e+02  4.29261705e+02 -1.27285715e-01 -1.59041314e-01]
 [ 7.96058632e+02  4.29996717e+02  2.37348206e-01 -9.05917682e-02]
 [ 7.95734218e+02  4.33333930e+02 -3.03937783e-01 -2.03823807e-01]
 ...
 [ 7.94641970e+02  4.29429368e+02 -8.10363023e-01  1.89604902e-01]
 [ 7.97467788e+02  4.31165025e+02  6.06602667e-02 -1.06024697e-01]
 [ 7.96077999e+02  4.31706565e+02 -3.11724088e-01  1.15451993e-01]]
[[ 7.94373328e+02  4.29919114e+02 -2.82377451e-01 -3.23183205e-01]
 [ 7.95678496e+02  4.28632852e+02  6.33727313e-02 -3.89304163e-01]
 [ 7.95103050e+02  4.29183066e+02 -5.29700867e-01 -4.22730863e-01]
 ...
 [ 7.96307008e+02  4.29853298e+02  3.68446386e-01 -1.87507743e-01]
 [ 7.94983496e+02  4.32088457e+02  9.28244457e-04 -1.05644125e-01]
 [ 7.96971651e+02  4.32829412e+02 -3.59879121e-01  2.74259909e-01]]
[[ 7.93364571e+02  4.34474923e+02 -1.09013890e+00  8.55950697e-01]
 [ 7.95883748e+02  4.29242574e+02 -3.43229306e-01 -3.21495264e-01]
 [ 7.96276199e+02  4.31906676e+02  1.07399373e-01 

[[ 7.98089624e+02  4.33124883e+02 -2.12865999e-02 -4.39149280e-01]
 [ 7.97177262e+02  4.34479477e+02 -5.70245953e-01 -1.31242508e-01]
 [ 7.97637020e+02  4.33166036e+02 -2.27402482e-01 -1.27498083e-01]
 ...
 [ 7.97003303e+02  4.33214073e+02  1.95284078e-01 -1.17230660e-01]
 [ 7.98912561e+02  4.34991613e+02 -2.45175252e-01  1.17133473e-02]
 [ 7.97770782e+02  4.35918095e+02 -3.30467353e-01  4.25612573e-01]]
[[ 7.99090782e+02  4.36498523e+02 -4.67111150e-02  2.63654187e-02]
 [ 7.97989168e+02  4.37991845e+02 -8.99766047e-02  2.60889398e-03]
 [ 7.99000723e+02  4.35708302e+02  4.04707009e-01  6.66692144e-01]
 ...
 [ 7.97320697e+02  4.36339957e+02 -1.51828023e-01  5.68549462e-01]
 [ 7.99327529e+02  4.36789571e+02  1.21560981e-01  1.41248045e-01]
 [ 7.99142936e+02  4.35109334e+02  2.00292401e-01  1.52732544e-01]]
[[ 7.97940850e+02  4.36861871e+02 -3.26014309e-01  4.72416893e-01]
 [ 7.98413313e+02  4.39499435e+02  2.38493534e-03  9.78634863e-01]
 [ 8.00465438e+02  4.34903369e+02  6.02484006e-01 

[[ 7.96772086e+02  4.29432345e+02 -4.88550276e-02 -1.92716700e-01]
 [ 7.96962834e+02  4.30923737e+02  7.86668304e-02 -5.28862549e-01]
 [ 7.96420189e+02  4.32121143e+02 -1.46296179e-01 -2.57967608e-01]
 ...
 [ 7.96782572e+02  4.32281008e+02  9.16132088e-02  4.46680784e-01]
 [ 7.96657496e+02  4.30895658e+02 -5.81042114e-01 -1.31876866e-01]
 [ 7.97147417e+02  4.30800557e+02 -2.39368196e-01  4.72688616e-02]]
[[ 7.97394797e+02  4.31050481e+02 -2.86954180e-01 -5.10488180e-01]
 [ 7.96655253e+02  4.29374532e+02 -2.44844657e-01 -1.69390452e-01]
 [ 7.96954485e+02  4.32930816e+02 -6.58363503e-02  7.74295504e-03]
 ...
 [ 7.94780485e+02  4.29304444e+02 -4.16845615e-01  1.76323652e-04]
 [ 7.96520730e+02  4.30389687e+02  1.11223686e-01 -1.20621524e-02]
 [ 7.95705043e+02  4.31489964e+02  3.39082322e-01  3.76655363e-01]]
[[ 7.97069549e+02  4.30071149e+02  4.56992980e-01 -1.09231479e-02]
 [ 7.95908955e+02  4.31290115e+02  8.17933607e-02 -1.57186734e-01]
 [ 7.95341645e+02  4.32028792e+02 -2.52815387e-01 

In [35]:
import cv2
import numpy as np

# Create a VideoCapture object
capture = cv2.VideoCapture('Trafic.mp4')

# Set up the desired color range (in this case, red)
lower_red = np.array([0, 100, 100])
upper_red = np.array([10, 255, 255])

while True:
    # Read a frame from the video
    ret, frame = capture.read()

    # Check if the video has ended
    if not ret:
        break

    # Convert the frame to the HSV color space
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Create a mask that only includes pixels within the color range
    mask = cv2.inRange(hsv, lower_red, upper_red)

    # Apply the mask to the frame
    result = cv2.bitwise_and(frame, frame, mask=mask)

    # Show the result
    cv2.imshow('Result', result)
    print(result)

    # Check if the user has pressed the 'q' key
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the VideoCapture object
capture.release()

# Close all windows
cv2.destroyAllWindows()


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...


In [19]:
import cv2
import numpy as np

# Create a VideoCapture object
capture = cv2.VideoCapture('Trafic.mp4')

while True:
    # Read a frame from the video
    ret, frame = capture.read()

    # Check if the video has ended
    if not ret:
        break

    # Convert the frame to the HSV color space
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

    # Define the range of colors to detect
    lower_color = np.array([0, 0, 0])
    upper_color = np.array([255, 255, 255])

    # Create a mask that only includes pixels within the color range
    mask = cv2.inRange(hsv, lower_color, upper_color)

    # Calculate the color histogram of the mask
    histogram = cv2.calcHist([mask], [0], None, [256], [0, 256])

    # Find the index of the dominant color
    dominant_color_index = np.argmax(histogram)

    # Map the index to a color value
    dominant_color = dominant_color_index

    # Print the dominant color
    print(dominant_color)

    # Check if the user has pressed the 'q' key
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the VideoCapture object
capture.release()

# Close all windows
cv2.destroyAllWindows()


255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
255
